# serverless.yml
service: security-aws-cognito-api-gateway

frameworkVersion: "3"
configValidationMode: warn
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-lift
  - serverless-add-api-key
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: "us-east-1"
  profile: rogerfelipensk
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
custom: ${file(yml/custom.yml)}
constructs: ${file(yml/constructs.yml)}
package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!test/**"
    - "!src/**/*.spec.ts"
    - "!src/**/*.spec.js"
functions:
  - ${file(yml/functions/app.yml)}
